### PR TITLE
fixed undefined method +  for nil:NilClass

### LINKED ISSUE #1901: loans#confirm (ActiveRecord::StatementInvalid) "PG::UndefinedColumn: ERREUR: la colonne « nan » n'existe pa...
## Error
An ActiveRecord::StatementInvalid occurred in loans#confirm:

  PG::UndefinedColumn: ERREUR:  la colonne « nan » n'existe pas
LIGNE 1 : UPDATE "loan_repayments" SET "base_amount" = NaN, "remaining...
                                                       ^
: UPDATE "loan_repayments" SET "base_amount" = NaN, "remaining_amount" = NaN, "amount" = NaN, "updated_at" = '2017-05-17 15:11:27.271319', "lock_version" = 1 WHERE "loan_repayments"."id" = $1 AND "loan_repayments"."lock_version" = $2
  app/models/loan.rb:207:in `block in generate_repayments'

---
## Environment
- **Version :** 2.44.1
- **Server :** preprod
- **Date :** 17/05/2017

### PR DESCRIPTION
**Pull request by chetannibotechnologies**
Fixes #1901.

### CODE REVIEW

File: app/models/loan_repayment.rb [hunk 1]
```diff
@@ -66,7 +66,7 @@ class LoanRepayment < Ekylibre::Record::Base
   }
 
   before_validation do
-    self.amount = base_amount + insurance_amount + interest_amount
+    self.amount = base_amount + insurance_amount + interest_amount rescue 0
```
Comment (burisu) [inline app/models/loan_repayment.rb]: Can you avoid use of `rescue`. Instead of that, can you add a default assignment on each amount (`xxx_amount ||= 0`)

File: app/models/loan_repayment.rb [hunk 2]
```diff
@@ -66,7 +66,7 @@ class LoanRepayment < Ekylibre::Record::Base
   }
 
   before_validation do
-    self.amount = base_amount + insurance_amount + interest_amount
+    self.amount = base_amount ||= 0 + insurance_amount ||= 0 + interest_amount ||= 0
```
Comment (burisu) [inline app/models/loan_repayment.rb]: I didn't think that default assignment could be done inline. I don't know if this is causing the failure but the tests fail.
Maybe you can try to add them on separate lines:
```ruby
base_amount ||= 0
insurance_amount ||= 0
...
```
