### PR TITLE
Fixed error message for FinancialYear#Create started_on field

### LINKED ISSUE #1979: Unknow message on fiscal year when updating financial year fiscal declaration mode
update_fiscal_year

### 1- How to reproduce?

Update a fiscal year and change financial year fiscal declaration mode.

### 2- What is really expected?

The message have to claim why.

### 3- How to test it?

On https://demo.ekylibre.farm/backend/financial-years/20/edit?redirect=%2Fbackend%2Ffinancial-years

### PR DESCRIPTION
**Pull request by Zank94**
Fixes #1979

### CODE REVIEW

**Comment by Zank94** [comment]
[ekylibre:debug/gh#1979-change_error_message_create_financial_year](https://trello.com/c/dvBvY5WE/256-ekylibredebug-gh1979-changeerrormessagecreatefinancialyear)

File: .gitignore [hunk 1]
```diff
@@ -93,4 +93,5 @@ Procfile.*
 .gitconfig
 
 custom_plan.rb
-zeus.json
\ No newline at end of file
+zeus.json
+postegres_config
```
Comment (burisu) [inline .gitignore]: Remove this line please

File: app/models/entity.rb [hunk 2]
```diff
@@ -181,6 +181,7 @@ class Entity < Ekylibre::Record::Base
   scope :normal, -> { where(of_company: false) }
   scope :necessary_transporters, -> { where("transporter OR id IN (SELECT transporter_id FROM #{Parcel.table_name} WHERE state != 'sent' OR delivery_id IS NULL)").order(:last_name, :first_name) }
   scope :suppliers,    -> { where(supplier: true) }
+  scope :of_company,   -> { where(of_company: true) }
```
Comment (burisu) [inline app/models/entity.rb]: Please use instead class method define below which return the unique Entity record and not a relation
