### PR TITLE
Fix measure initialization unit related issues

### LINKED ISSUE #2139: interventions#compute (Measure::InvalidExpression) 0.017l/1000 pl. cannot be parsed.
Happens when creating a new intervention using specific products

### LINKED ISSUE #2140: interventions#compute (Measure::InvalidExpression) "5 cannot be parsed."
Happens when creating a new intervention using specific products

### PR DESCRIPTION
**Pull request by Zank94**
Fixes #2140, and fixes #2139

### CODE REVIEW

**Comment by Zank94** [comment]
[ekylibre:debug/gh2139-fix-measure-initialize-unit-related-issues](https://trello.com/c/pJZvF5C4/330-ekylibredebug-gh2139-fix-measure-initialize-unit-related-issues)

File: lib/pesticide/usage.rb [hunk 1]
```diff
@@ -4,13 +4,14 @@ class Usage
...
       @name = attributes.delete(:name)
-      @dose = Measure.new(attributes.delete(:dose)) if attributes[:dose]
+      @dose = (attributes[:dose] && attributes[:dose] =~ /\A-?([\,\.]\d+|\d+([\,\.]\d+)?)\s*[^\s]+\z/) ? Measure.new(attributes.delete(:dose)) : attributes.delete(:dose)
       @subject = attributes.delete(:subject) || {}
       @mode = attributes.delete(:mode)
       @issue = attributes.delete(:issue)
       @pre_harvest_interval = attributes[:pre_harvest_interval].in(:day) if attributes[:pre_harvest_interval]
       @max_inputs_count = attributes[:max_inputs_count]
       if attributes[:untreated_zone_distance]
+        attributes[:untreated_zone_distance] += 'm' if attributes[:untreated_zone_distance] =~ /\A-?([\,\.]\d+|\d+([\,\.]\d+)?)\z/
```
Comment (Aquaj) [inline lib/pesticide/usage.rb]: This should be changed to take advantage of `Measure.new`s capability to receive the unit_name as a second parameter rather than parsing the string.
You should have something like: `Measure.new(attributes[:untreated_zone_distance], :meter)` in your conditional to be more explicit and to avoid crashes in cases where `attributes[:untreated_zone_distance]` is a Numeric.
