### PR TITLE
Rewrote ProductNatureVariant#current_outgoing_stock_ordered_not_delivered to match both sale items and parcel items not related to sales

### LINKED ISSUE #2107: Calculation error in "not distributed order" column for Product Nature Variant
The value returned is wrong.
For example, Pommier - Malus M9 - 10/12 belongs to two different sales whose parcels were both given.
Thus, the value in "not distributed order" column should be 0 instead of 275.
issue

### PR DESCRIPTION
**Pull request by Zank94**
Fixes #2107

### CODE REVIEW

**Comment by Zank94** [comment]
[ekylibre:debug/2107-Fix-notdistributed-order-column-for-product-nature-variant-list](https://trello.com/c/xIfJ9uxn/309-ekylibredebug-2107-fix-notdistributed-order-column-for-product-nature-variant-list)

File: app/models/product_nature_variant.rb [hunk 1]
```diff
@@ -434,9 +434,8 @@ def current_stock
 
   # Return current quantity of all products link to the variant currently ordered or invoiced but not delivered
   def current_outgoing_stock_ordered_not_delivered
-    sales = Sale.where(state: %w[order invoice])
-    sale_items = SaleItem.where(variant_id: id, sale_id: sales.pluck(:id)).includes(:parcel_items).where(parcel_items: { sale_item_id: nil })
-    sale_items.map(&:quantity).compact.sum.to_f
+    sales_not_delivered = Sale.where(state: %w(order invoice)).includes(:parcels).where(parcels: { state: %w(draft ordered in_preparation prepared) })
+    SaleItem.where(variant_id: id, sale_id: sales_not_delivered.pluck(:id)).sum(:quantity).to_f
```
Comment (burisu) [inline app/models/product_nature_variant.rb]: @ionosphere said to me that the amount expected is the sum of ordered/invoiced quantity minus delivered quantity
