### PR TITLE
Custom field creation/update raises exception when customized_type is blank

### LINKED ISSUE #1862: custom_fields#update (NameError) "wrong constant name "
A NameError occurred in custom_fields#update:

  wrong constant name 
  app/models/custom_field.rb:79:in `block in <class:CustomField>'

* URL        : http://demo.ekylibre.farm/backend/custom-fields/1
* Parameters : { "custom_field"=>{"customized_type"=>"", "name"=>"Froid", "active"=>"1", "required"=>"0", "minimal_length"=>"", "maximal_length"=>"", "minimal_value"=>"0.0", "maximal_value"=>"1500.0"}, "id"=>"1"}

-------------------------------
Environment:
-------------------------------
- Version: 2.43.1
- Server: Production
- Date: 04/05/2017

### PR DESCRIPTION
**Pull request by pratap477**
Fixes #1862

### CODE REVIEW

File: app/controllers/backend/fixed_assets_controller.rb [hunk 1]
```diff
@@ -127,7 +127,7 @@ def depreciate_all
       end
 
       count = FixedAsset.depreciate(until: bookkeep_until)
-      notify_success(:x_fixed_asset_depreciations_have_been_bookkept_successfully, count: count)
+      notify_success(:"x_fixed_asset_depreciations_have_been_bookkept_successfully", count: count)
```
Comment (burisu) [inline app/controllers/backend/fixed_assets_controller.rb]: This change is not concerned by the PR. Can you remove it?

File: app/models/custom_field.rb [hunk 2]
```diff
@@ -76,7 +76,7 @@ class CustomField < Ekylibre::Record::Base
   end
 
   validate do
-    unless customized_type.to_s.constantize.respond_to?(:custom_fields)
+    unless customized_type.nil? || customized_type.to_s.constantize.respond_to?(:custom_fields)
```
Comment (burisu) [inline app/models/custom_field.rb]: For clearness purpose, can we rewrite condition like: `if customized_type.present? && !custom...` 
It 's seems to me more understandable

**Comment by burisu** [comment]
[ekylibre:debug/gh1862_fixed_wrong_constant_name](https://trello.com/c/bUsNsvfK/279-ekylibredebug-gh1862fixedwrongconstantname)
